// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG33Xxlh2SeC45zKpwLW-6bhl0mroHRfc',
    appId: '1:1020114810625:web:602333d6d6f15873904d00',
    messagingSenderId: '1020114810625',
    projectId: 'cursova-8f646',
    authDomain: 'cursova-8f646.firebaseapp.com',
    storageBucket: 'cursova-8f646.firebasestorage.app',
    measurementId: 'G-5MR0M6Y701',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0XOvE9OjDQHJS0ImOuc1YN_lDKHD-FjA',
    appId: '1:1020114810625:android:a1d01972a5348341904d00',
    messagingSenderId: '1020114810625',
    projectId: 'cursova-8f646',
    storageBucket: 'cursova-8f646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vtDTjvP9yrFBw6WYayhbY0dQi85RB8g',
    appId: '1:1020114810625:ios:66498ae00ffd84db904d00',
    messagingSenderId: '1020114810625',
    projectId: 'cursova-8f646',
    storageBucket: 'cursova-8f646.firebasestorage.app',
    iosBundleId: 'com.shadow.photoapp.untitledsdsf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vtDTjvP9yrFBw6WYayhbY0dQi85RB8g',
    appId: '1:1020114810625:ios:66498ae00ffd84db904d00',
    messagingSenderId: '1020114810625',
    projectId: 'cursova-8f646',
    storageBucket: 'cursova-8f646.firebasestorage.app',
    iosBundleId: 'com.shadow.photoapp.untitledsdsf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG33Xxlh2SeC45zKpwLW-6bhl0mroHRfc',
    appId: '1:1020114810625:web:91caf2b7faa19517904d00',
    messagingSenderId: '1020114810625',
    projectId: 'cursova-8f646',
    authDomain: 'cursova-8f646.firebaseapp.com',
    storageBucket: 'cursova-8f646.firebasestorage.app',
    measurementId: 'G-M8BYX73FNX',
  );
}
